ppojastores/trunk/PoojaStores/Models/Repositories/Entity/Cart.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PoojaStores.Models.Repositories.Entity
{
    public class Cart
    {
        [Key]
        public int CartId { get; set; }
        public int? CartUserId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string CurrentStatus { get; set; }
        public bool? IsDeleted { get; set; }
        public int addressId { get; set; }
        public string OrderNotes { get; set; }
    }
}

ppojastores/trunk/PoojaStores/Models/Repositories/Entity/WishList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PoojaStores.Models.Repositories.Entity
{
    public class WishList
    {
        [Key]
        public int WishListId { get; set; }
        public int? UserId { get; set; }
        public int? ProductId { get; set; }
        public int? ProductDetailId { get; set; }
        public DateTime? AddedOn { get; set; }
        public bool? IsDeleted { get; set; }
    }
}

ppojastores/trunk/PoojaStores/Controllers/SalesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using PoojaStores.Models.ModelClasses;
using PoojaStores.Models.Repositories.Entity;
using PoojaStores.Models.Services.Interfaces;
using PoojaStores.Models.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PoojaStores.Controllers
{
    public class SalesController : Controller
    {
        private readonly ISalesMgmtService iService;
        private readonly ICommonDropsMgmtService cService;
        private readonly IProductMgmtService pService;
        private readonly IPaymentService payService;
        private readonly IConfiguration _config;
        private readonly IUsersMgmtService uService;
        private readonly INotificationService notificationService;
        private readonly IMasterMgmtService mService;
        public SalesController(ISalesMgmtService _iService, ICommonDropsMgmtService _cService, IProductMgmtService _pService,
            IPaymentService _payService, IConfiguration config, IUsersMgmtService _uService , INotificationService _NService,IMasterMgmtService _mService)
        {
            iService = _iService;
            cService = _cService;
            pService = _pService;
            payService = _payService;
            _config = config;
            uService = _uService;
            notificationService = _NService;
            mService = _mService;
        }
        [HttpPost]
        public IActionResult SaveWishList(int id)
        {
            LoginResponse loginCheckResponse = new LoginResponse();
            loginCheckResponse = SessionHelper.GetObjectFromJson<LoginResponse>(HttpContext.Session, "loggedUser");
            if (loginCheckResponse == null)
            {
                ProcessResponse p = new ProcessResponse();
                p.statusCode = 5;
                p.statusMessage = "Please Login";
                return Json(new { result = p });
            }
            ViewBag.LoggedUser = loginCheckResponse;
            bool res = iService.IsProduct(id, loginCheckResponse.userId);
            ProcessResponse pr = new ProcessResponse();
            if (res)
            {
                pr.statusCode = 0;
                pr.statusMessage = "Already Existed";
                return Json(new { result = pr });
            }
            else
            {
                bool resu = iService.IsCart(loginCheckResponse.userId, id);
                if (resu)
                {
                    pr.statusCode = 4;
                    pr.statusMessage = "Already In Cart";
                    return Json(new { result = pr });
                }
                else
                {
                    WishList wl = new WishList();
                    wl.UserId = loginCheckResponse.userId;
                    wl.ProductId = id;
                    wl.AddedOn = DateTime.Now;
                    wl.IsDeleted = false;
                    pr = iService.SaveWishList(wl);
                    return Json(new { result = pr });
                }
            }
        }

        public IActionResult MoveToWishlist(int id)
        {
            LoginResponse loginCheckResponse = new LoginResponse();
            loginCheckResponse = SessionHelper.GetObjectFromJson<LoginResponse>(HttpContext.Session, "loggedUser");
            if (loginCheckResponse == null)
            {
                ProcessResponse p = new ProcessResponse();
                p.statusCode = 5;
                p.statusMessage = "Please Login";
                return Json(new { result = p });
            }
            ViewBag.LoggedUser = loginCheckResponse;

            CartDetails cd = iService.GetCartDetailsMaster(id);
            cd.IsDeleted = true;        
            ProcessResponse pr= iService.SaveCartDetails(cd);
            if (pr.statusCode == 1)
            {
                WishList wl = new WishList();
                wl.UserId = loginCheckResponse.userId;
                wl.ProductId = cd.ProductId;
                wl.AddedOn = DateTime.Now;
                wl.IsDeleted = false;
                pr = iService.SaveWishList(wl);                
            }
            return RedirectToAction("WishList");
        }

        public IActionResult WishList()
        {
            LoginResponse loginCheckResponse = new LoginResponse();
            loginCheckResponse = SessionHelper.GetObjectFromJson<LoginResponse>(HttpContext.Session, "loggedUser");
            if (loginCheckResponse == null)
            {
                return RedirectToAction("Login", "Authenticate", new { url = "Sales/Wishlist" });
            }
            ViewBag.LoggedUser = loginCheckResponse;
            ViewBag.HeadCats = cService.GetCatsWithSubCats();

            List<ProductDisplayModel> pm = iService.GetWishListProducts(loginCheckResponse.userId);

            List<CartDetails> list = iService.GetCartProducts(loginCheckResponse.userId);
            ViewBag.cartprods = list;
            ViewBag.CartCount = list.Count;
            return View(pm);
        }

        public IActionResult SaveCart(int id, int qty = 0)
        {
            ProcessResponse pr = new ProcessResponse();
            LoginResponse loginCheckResponse = new LoginResponse();
            loginCheckResponse = SessionHelper.GetObjectFromJson<LoginResponse>(HttpContext.Session, "loggedUser");
            if (loginCheckResponse == null)
            {
                pr.statusCode = 5;
                pr.statusMessage = "Please Login";
                return Json(new { result = pr });
            }
            ProductHomeDisplayModel prod = pService.GetProDisplMdl(id);
            if (qty == 0)
            {
                qty = (int)prod.MinimumOrderQty;
            }
            if (qty > prod.QtyAvailable || qty<prod.MinimumOrderQty)
            {
                
                if (qty > prod.QtyAvailable)
                {
                    pr.statusCode = 2;
                    pr.statusMessage = "Out Of Stock";
                }
                else
                {
                    pr.statusCode = 3;
                    pr.statusMessage = "Please Select Minimim Order Quantitty";
                }
                return Json(new { result = pr });
            }
            else
            {
                Cart old = iService.GetCartById(loginCheckResponse.userId);
                if (old == null)
                {
                    Cart c = new Cart();

                    c.CartUserId = loginCheckResponse.userId;
                    c.CreatedOn = DateTime.Now;
                    c.IsDeleted = false;
                    c.CurrentStatus = "Open";
                    pr = iService.SaveCart(c);
                    old = iService.GetCartById(loginCheckResponse.userId);
                }
                CartDetails cd = iService.GetCartDetailsById(old.CartId, id);
                if (cd == null)
                {
                    CartDetails crtdet = new CartDetails();
                    crtdet.CartId = old.CartId;
                    crtdet.ProductId = id;
                    crtdet.Image1 = prod.Image1;
                    crtdet.Title = prod.Title;
                    crtdet.Price = prod.DiscountedPrice;
                    crtdet.GStPrice = prod.GSTPrice;
                    crtdet.NumberProducts = qty;
                    crtdet.CurrentStatus = "Open";
                    crtdet.AdededOn = DateTime.Now;
                    crtdet.IsDeleted = false;
                    pr = iService.SaveCartDetails(crtdet);
                }
                else
                {
                    pr.statusCode = 0;
                    pr.statusMessage = "Already Exists";
                }

                WishList w = iService.GetProductsByProductId(loginCheckResponse.userId, id);

                if (w != null)
                {
                    w.IsDeleted = true;
                    ProcessResponse p = iService.SaveWishList(w);
                }
                return Json(new { result = pr });
            }
        }

        public IActionResult Cart(int id)
        {
            LoginResponse loginCheckResponse = new LoginResponse();
            loginCheckResponse = SessionHelper.GetObjectFromJson<LoginResponse>(HttpContext.Session, "loggedUser");
            if (loginCheckResponse == null)
            {
                return RedirectToAction("Login", "Authenticate", new { url = "Sales/Cart" });
            }
            ViewBag.LoggedUser = loginCheckResponse;
            ViewBag.HeadCats = cService.GetCatsWithSubCats();
            List<CartDetails> list = iService.GetCartProducts(loginCheckResponse.userId);
            ViewBag.cartprods = list;
            ViewBag.CartCount = list.Count;

            return View(list);
        }

        public IActionResult UpdateCart(int cartId, int newCnt)
        {
            ProcessResponse pr = new ProcessResponse();
            LoginResponse loginCheckResponse = new LoginResponse();
            loginCheckResponse = SessionHelper.GetObjectFromJson<LoginResponse>(HttpContext.Session, "loggedUser");
            if (loginCheckResponse == null)
            {
                pr.statusCode = 5;
                pr.statusMessage = "Please Login";
                return Json(new { result = pr });
            }

            CartDetails c = iService.GetCartDetailsMaster(cartId);

            ProductMain pm = pService.GetProductById((int)c.ProductId);
            if (pm.QtyAvailable >= newCnt)
            {
                c.NumberProducts = newCnt;
                pr = iService.SaveCartDetails(c);
            }
            else
            {
                pr.statusCode = 0;
                pr.statusMessage = "Requested Qty Exceds Available Qty";
            }
            return Json(new { result = pr });
        }

        public IActionResult SaveAddress(Address request)
        {
            LoginResponse loginCheckResponse = new LoginResponse();

ppojastores/trunk/PoojaStores/Views/Sales/CODDone.cshtml
<div class="container-fluid d-flex flex-column align-items-center bg-gray p-4">
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item disabled">
                    <a href="~/Sales/Cart">
                        Shopping Cart
                    </a>
                </li>

                <li class="breadcrumb-item disabled" aria-current="page">
                    <a href="~/Sales/CheckOut">
                        Checkout
                    </a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                    Order Complete
                </li>
            </ol>
        </div>
    </nav>
</div>


<div class="content" style="text-align:center;width:40%;margin-top:5%;margin-left:30%;margin-bottom:10%">
    <div class="card all_btn_card" id="lobicard-custom-control1" data-sortable="true" style="text-align:center;">
        <br />
        <h3 class="text-success">Success</h3>
        <br />
    </div>
</div>

ppojastores/trunk/PoojaStores/Views/Sales/Cart.cshtml
@model IEnumerable<PoojaStores.Models.Repositories.Entity.CartDetails>
@{
    decimal totalPrice = 0;
    decimal tx =0;
    decimal totwithTax = 0;
    System.Globalization.CultureInfo Indian = new System.Globalization.CultureInfo("hi-IN");
}
<main class="main">
    <div class="container">
        @*<ul class="checkout-progress-bar d-flex justify-content-center flex-wrap mt-2">
            <li class="active">
                <a href="cart.html">Shopping Cart</a>
            </li>
            <li>
                <a href="checkout.html">Checkout</a>
            </li>
            <li class="disabled">
                <a href="cart.html">Order Complete</a>
            </li>
        </ul>*@
    <br />
    <br />
        @if (ViewBag.CartCount > 0)
        {
            <div class="row">
            <div class="col-lg-8">
                <div class="cart-table-container">
                    <table class="table table-cart">
                        <thead>
                            <tr>
                                <th class="thumbnail-col"></th>
                                <th class="product-col">Product</th>
                                <th class="price-col">Price</th>
                                <th class="qty-col">Quantity</th>
                                <th class="text-right">Subtotal</th>
                                <th class="text-right">Add to wishList</th>
                                <th class="text-right">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var p in Model)
                            {
                            <tr class="product-row">
                                <td>
                                    <figure class="product-image-container">

                                        <a href="~/Home/ProductDetails?id=@p.ProductId" class="product-image">
                                            <img src="~/ProductImages/@p.Image1" width="100" height="100" alt="product">
                                        </a>

                                    </figure>
                                    @*<a href="#" class="btn-remove icon-cancel" title="Remove Product"></a>*@
                                </td>
                                <td class="product-col">
                                    <h5 class="product-title">
                                        <a href="~/Home/ProductDetails?id=@p.ProductId">@p.Title</a>
                                    </h5>
                                </td>
                                <td>@(String.Format(Indian, "{0:N}", p.Price))</td>
                                <td>
                                    <div class="product-single-qty">
                                        <div class="input-group">
                                            <input type="button" value="-" class="button-minus border rounded-circle  icon-shape icon-sm mx-1 " data-field="quantity" onclick="minuCart(@p.CartDetailId)">
                                            <input step="1" max="10" id="ccnt_@p.CartDetailId" value="@p.NumberProducts" name="quantity" class="quantity-field border-0 text-center w-25" readonly>
                                            <input type="button" value="+" class="button-plus border rounded-circle icon-shape icon-sm " data-field="quantity"onclick="plusCart(@p.CartDetailId)">
                                        </div>
                                    </div>
                                    @*<br /><br /><br />
                                    <button onclick="updCrt(@p.CartId)">Update Cart</button>*@
                                </td>
                                @{
                                    var price = p.Price * p.NumberProducts;
                                    totalPrice += (decimal)price;
                                    var singletax = p.GStPrice * p.NumberProducts;
                                    tx += (decimal)singletax;
                                }
                                <td class="text-right"><span class="subtotal-price" id="singleTotal_@p.CartId">@(String.Format(Indian, "{0:N}", price))</span></td>
                                <td class="text-right"> <a href="~/Sales/MoveToWishlist?id=@p.CartDetailId" class="btn btn-primary btn-sm">Move to Wishlist</a></td>
                                <td class="text-right">
                                    <a href="javascript:void(0)" onclick="ShowDelete(@p.CartDetailId)">
                                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                                    }                           
                        </tbody>
                        <!--<tfoot>
                            <tr>
                                <td colspan="5" class="clearfix">
                                    <div class="float-left">
                                        <div class="cart-discount">
                                            <form action="#">
                                                <div class="input-group">
                                                    <input type="text" class="form-control form-control-sm"
                                                           placeholder="Coupon Code" required>
                                                    <div class="input-group-append">
                                                        <button class="btn btn-sm" type="submit">
                                                            Apply
                                                            Coupon
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>

                                    <div class="float-right">
                                        <button type="submit" class="btn btn-shop btn-update-cart">
                                            Update Cart
                                        </button>
                                    </div>
                                <!--</td>
                            </tr>
                        </tfoot>-->
                    </table>
                </div><!-- End .cart-table-container -->
            </div><!-- End .col-lg-8 -->

            <div class="col-lg-4 ">
                <div class="cart-summary">
                    <h4>CART TOTAL</h4>

                    <table class="table table-totals">
                        <tbody>
                            <tr>
                                <td>Subtotal</td>
                                <td><h5>@(String.Format(Indian, "{0:N}", totalPrice))</h5></td>
                            </tr>
                            <tr>
                                <td>Tax Amount</td>
                                <td><h5>@(String.Format(Indian, "{0:N}", tx))</h5></td>
                            </tr>                      
                        </tbody>
                        @{ totwithTax = totalPrice + tx;}
                        <tfoot>
                            <tr>
                                <td>Total With Taxes</td>
                                <td><h5>@(String.Format(Indian, "{0:N}", totwithTax))</h5></td>
                            </tr>
                        </tfoot>
                    </table>
                @if (Model.Count() > 0)
                {
                    <div class="checkout-methods">
                        <a href="~/Sales/CheckOut" class="btn btn-block btn-dark">
                            Proceed to Checkout
                            <i class="fa fa-arrow-right"></i>
                        </a>
                    </div>
                }


                </div><!-- End .cart-summary -->
            </div><!-- End .col-lg-4 -->
        </div><!-- End .row -->
            }
            else
            {
                <a href="~/Home/Index" class="btn btn-primary">Go Shop</a>
            }
    </div><!-- End .container -->

    <div class="mb-6"></div><!-- margin -->
</main>
@*<script>
    function incrementValue(e) {
        e.preventDefault();
        var fieldName = $(e.target).data('field');
        var parent = $(e.target).closest('div');
        var currentVal = parseInt(parent.find('input[name=' + fieldName + ']').val(), 10);

        if (!isNaN(currentVal)) {
            parent.find('input[name=' + fieldName + ']').val(currentVal + 1);
        } else {
            parent.find('input[name=' + fieldName + ']').val(0);
        }
    }
    function decrementValue(e) {
        e.preventDefault();
        var fieldName = $(e.target).data('field');
        var parent = $(e.target).closest('div');
        var currentVal = parseInt(parent.find('input[name=' + fieldName + ']').val(), 10);

        if (!isNaN(currentVal) && currentVal > 1) {
            parent.find('input[name=' + fieldName + ']').val(currentVal - 1);
        } else {
            parent.find('input[name=' + fieldName + ']').val(1);
        }
    }
    $('.input-group').on('click', '.button-plus', function (e) {
        incrementValue(e);
    });

    $('.input-group').on('click', '.button-minus', function (e) {
        decrementValue(e);
    });
</script>*@
<script>
    //var oldtotal =@totalPrice;
    function ShowDelete(id) {
        swal("Are you sure?", {
            buttons: {
                yes: {
                    text: "Yes",
                    value: "yes"
                },
                no: {
                    text: "No",
                    value: "no"
                }
            }
        }).then((value) => {
            if (value === "yes") {
                $.ajax({
                    url: GlobalUrl + "Sales/DeleteCart?id=" + id,
                    type: 'post',
                    data: '{}',
                    success: function (result) {
                        toastr["success"]("Successuflly deleted!");
                        window.location.href = window.location.href;
                    }
                });
            }
            else {
                toastr["error"]("Delete cancelled!");
            };
        });
    }
    function updCrt(id) {
        var newcnt = $("#ccnt_" + id).val();
        $.ajax({
            url: GlobalUrl + "Sales/UpdateCart?cartId=" + id + "&newCnt=" + newcnt,
            type: 'post',
            date: '{}',
            success: function (res) {
                if (res.result.statusCode == 1) {
                    toastr["success"]("Successuflly Updated");
                    window.location.href = window.location.href;
                } else {
                    toastr["error"](res.result.statusMessage);
                }
            }
        })
    }
    function minuCart(id) {
        var newcnt = $("#ccnt_" + id).val();        
        if (newcnt != '1') {
            var cnt = parseInt(newcnt) - 1;
            $.ajax({
                url: GlobalUrl + "Sales/UpdateCart?cartId=" + id + "&newCnt=" + cnt,
                type: 'post',
                date: '{}',
                success: function (res) {
                    if (res.result.statusCode == 1) {
                        //toastr["success"]("Successuflly Updated");
                        //var mul = cnt * price;
                        //var str = mul.toString();
                        //$("#singleTotal_" + id).text(str + ".00");
                        //var tot = oldtotal;
                        //var newtot = tot - price;
                        //var nt = newtot + ".00";
                        //$("#tot").text(nt);
                        //oldtotal = newtot;
                        //$("#ccnt_" + id).val(cnt);
                        window.location.href=window.location.href;
                    } else {
                        toastr["error"](res.result.statusMessage);
                    }
                }
            })
        } else {
            toastr["error"]("Min Order Qty Should be 1");
        }
    }
    function plusCart(id) {
        var newcnt = $("#ccnt_" + id).val();
        var cnt = parseInt(newcnt) + 1;
        $.ajax({
            url: GlobalUrl + "Sales/UpdateCart?cartId=" + id + "&newCnt=" + cnt,
            type: 'post',
            date: '{}',
            success: function (res) {
                if (res.result.statusCode == 1) {
                    //toastr["success"]("Successuflly Updated");
                    //var mul = cnt * price;
                    //var str = mul.toString();
                    //$("#singleTotal_" + id).text(str + ".00");
                    //var tot = oldtotal;
                    //var newtot = tot + price;
                    //var nt = newtot + ".00";
                    //$("#tot").text(nt);
                    //oldtotal = newtot;
                    //$("#ccnt_" + id).val(cnt);
                    window.location.href=window.location.href;
                } else {
                    toastr["error"](res.result.statusMessage);
                }
            }
        })
    }
</script>

ppojastores/trunk/PoojaStores/Views/Sales/CodSuccess.cshtml
<div class="container-fluid d-flex flex-column align-items-center bg-gray p-4">
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item disabled">
                    <a href="~/Sales/Cart">
                        Shopping Cart
                    </a>
                </li>
                
                <li class="breadcrumb-item disabled" aria-current="page"><a href="~/Sales/CheckOut"></a>
                    Checkout
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                    Order Complete
                </li>
            </ol>
        </div>
    </nav>
</div>

ppojastores/trunk/PoojaStores/Views/Sales/CreateOrder.cshtml
@model PoojaStores.Models.ModelClasses.OrderModel

<button id="rzp-button1" hidden>Pay</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "@Html.DisplayFor(model => model.razorpayKey)", // Enter the Key ID generated from the Dashboard
    "amount": "@Html.DisplayFor(model => model.amount)", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "@Html.DisplayFor(model => model.currency)",
    "name": "@Html.DisplayFor(model => model.name)",
    "description": "@Html.DisplayFor(model => model.description)",
    "image": "http://staging.heeranyam.com/WebApp/assets/img/logo/logo.png", // You can give your logo url
    "order_id": "@Html.DisplayFor(model => model.orderId)",
    "handler": function (response){
        // After payment successfully made response will come here
        // Set the data in hidden form
        document.getElementById('rzp_paymentid').value = response.razorpay_payment_id;
        document.getElementById('rzp_orderid').value = response.razorpay_order_id;

        // // Let's submit the form automatically
        document.getElementById('rzp-paymentresponse').click();
    },
    "prefill": {
        "name": "@Html.DisplayFor(model => model.name)",
        "email": "@Html.DisplayFor(model => model.email)",
        "contact": "@Html.DisplayFor(model => model.contactNumber)"
    },
    "notes": {
        "address": "@Html.DisplayFor(model => model.address)"
    },
    "theme": {
        "color": "#F37254"
    }
};
var rzp1 = new Razorpay(options);

//<!-- onload function -->
window.onload = function(){
    document.getElementById('rzp-button1').click();
};

document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>

<!-- This form is hidden, and submit when payment successfully made -->
@using (Html.BeginForm("Complete", "Sales"))
{
    @Html.AntiForgeryToken()

    @Html.Hidden("rzp_paymentid")
    @Html.Hidden("rzp_orderid")
    <button type="submit" id="rzp-paymentresponse" class="btn btn-primary" hidden>Submit</button>
}




<!-- breadcrumb area start -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb-wrap">
                    <nav aria-label="breadcrumb">
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="~/Home/Index"><i class="fa fa-home"></i></a></li>
                            <li class="breadcrumb-item active" aria-current="page">Payment</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb area end -->
<!-- login register wrapper start -->
<div class="login-register-wrapper section-padding loginBanner">
    <div class="container">
        <div class="member-area-from-wrap">
            <div class="row">
                <!-- Login Content Start -->
                <div class="offset-md-12 col-lg-12">
                    <div class="login-reg-form-wrap">
                        <h5>Redirecting to payment gateway... please wait!</h5>
                        <div class="table-responsive table-desi">
                            <div class="minicart-item-wrapper">


                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

ppojastores/trunk/PoojaStores/Views/Sales/PaymentFailed.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

    <div class="container-fluid d-flex flex-column align-items-center bg-gray p-4">
        <nav aria-label="breadcrumb" class="breadcrumb-nav">
            <div class="container">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item disabled">
                        <a href="~/Sales/Cart">
                            Shopping Cart
                        </a>
                    </li>

                    <li class="breadcrumb-item disabled" aria-current="page">
                        <a href="~/Sales/CheckOut">
                            Checkout
                        </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Order Complete
                    </li>
                </ol>
            </div>
        </nav>
    </div>


    <div class="content" style="text-align:center;width:40%;margin-top:5%;margin-left:30%;margin-bottom:10%">
        <div class="card all_btn_card" id="lobicard-custom-control1" data-sortable="true" style="text-align:center;">
            <br />
            <h3 class="text-danger">Payment Failed!</h3>
            <br />
        </div>
    </div>